In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import cv2

In [ ]:
import os
import csv

In [ ]:
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [ ]:
folder1 = "/content/drive/MyDrive/Cyclist/with_helmet"
folder2 = "/content/drive/MyDrive/Cyclist/without_helmet"

In [ ]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,150)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'/content/drive/MyDrive/Cyclist/helmet_data.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (290, 128)
descriptor shape  1  :  (255, 128)
descriptor shape  2  :  (173, 128)
descriptor shape  3  :  (161, 128)
descriptor shape  4  :  (88, 128)
descriptor shape  5  :  (32, 128)
descriptor shape  6  :  (142, 128)
descriptor shape  7  :  (262, 128)
descriptor shape  8  :  (224, 128)
descriptor shape  9  :  (175, 128)
descriptor shape  10  :  (107, 128)
descriptor shape  11  :  (308, 128)
descriptor shape  12  :  (218, 128)
descriptor shape  13  :  (252, 128)
descriptor shape  14  :  (82, 128)
descriptor shape  15  :  (180, 128)
descriptor shape  16  :  (281, 128)
descriptor shape  17  :  (173, 128)
descriptor shape  18  :  (128, 128)
descriptor shape  19  :  (136, 128)
descriptor shape  20  :  (247, 128)
descriptor shape  21  :  (116, 128)
descriptor shape  22  :  (204, 128)
descriptor shape  23  :  (210, 128)
descriptor shape  24  :  (231, 128)
descriptor shape  25  :  (200, 128)
descriptor shape  26  :  (199, 128)
descriptor shape  27  :  (294, 128)
descr

In [ ]:
data1 = pd.read_csv(r'/content/drive/MyDrive/Cyclist/helmet_data.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         1    0   10  130   49    9    9   21    2    2  ...   31    1    0   
1         0    1    5    0    0    3    2    0    6   10  ...   20   27   99   
2        32    8    7    3    0    1    2    4  186    4  ...    1    9    0   
3         0    0    2    8   42   17    1    0    7    3  ...   19   92    0   
4        14   12    5    3    2    1    2    4  130   70  ...    3  127   14   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
537124   19  146    9    2    9   49   55   11   13   32  ...   15   61    1   
537125    3    0    0    1    3    0    1    3  142   36  ...   20   21    0   
537126    9   26   43   67   52   10    0    0   46    9  ...    0    0   10   
537127   20   26    8   13   86   76    1    0  147  126  ...    0    0   12   
537128    8    1    3   98   78   33   14    8   21    1  ...    0    2   16   

        121  122  123  124  125  126  127  
0         0    0    0    0    0    0    0  
1         7    6   27   14    0   10   62  
2         0    0    0    0    0    0    0  
3         0    0    0    0    5    3    1  
4        21   19    0    0    0    4    5  
...     ...  ...  ...  ...  ...  ...  ...  
537124    1    0    0    0    0    0    0  
537125    0    0    0    0    0    1    3  
537126    9    0    0    0    0    0    0  
537127  147   50    0    0    0    0    0  
537128  143   16    0    0    0    0    0  

[537129 rows x 128 columns]

In [ ]:
i=1
for filename in os.listdir(folder2):
    #path
    path=os.path.join(folder2,filename)
    b=cv2.imread(path)
    
    #resize image
    resize=(150,150)
    img=cv2.resize(b,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'/content/drive/MyDrive/Cyclist/nohelmet_data.csv', mode='a', header=False,index=False)

In [ ]:
data2= pd.read_csv(r'/content/drive/MyDrive/Cyclist/nohelmet_data.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         0    0    0    0    0    0    0    0   50    2  ...    3   38   10   
1         2    2    2    0    0    0    0    1   65   65  ...    1    3    5   
2        89   14    2    2    0    0    0   10  161   44  ...    2    9    0   
3        34   22   29   12    0    0    0    2  161   48  ...    1    6    0   
4        45   16    1    0    0    0    0    0  151   48  ...   15    3    1   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
708415   15    3    2    1    5  124  132   12    7    0  ...    0    0    0   
708416    5    0    0    0   10   98  111   33   56    2  ...    0    0    0   
708417   16  155   50    2    6    1    0    0   27  134  ...    0    2    0   
708418   87   94    9    0    4   22    5   20   46   79  ...   12   10    0   
708419    1    2    0    0    0    0    1    0    8    3  ...    0   27   76   

        121  122  123  124  125  126  127  
0         3    2   12  149   28    2    5  
1         7   92   53    2    1    1   21  
2         0    0    0   13    7    0    0  
3         0    0    0   33    5    0    0  
4         0    0    0    1    7   22   21  
...     ...  ...  ...  ...  ...  ...  ...  
708415    0    1    0    0    0    0    0  
708416    0    0    0    0    0    0    0  
708417    0    0    0    0    0    0    0  
708418    0    0    6   85   12    0    0  
708419    0    0    9   60   12    0    7  

[708420 rows x 128 columns]

In [ ]:
data=data1.append(data2)

In [ ]:
csv_data=data.to_csv(r'/content/drive/MyDrive/Cyclist/detect_helmet1.csv', mode='a', header=False,index=False)

In [ ]:
data= pd.read_csv(r'/content/drive/MyDrive/Cyclist/detect_helmet1.csv',header=None,dtype='uint8')
data=data.astype(np.uint8)
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0          1    0   10  130   49    9    9   21    2    2  ...   31    1    0   
1          0    1    5    0    0    3    2    0    6   10  ...   20   27   99   
2         32    8    7    3    0    1    2    4  186    4  ...    1    9    0   
3          0    0    2    8   42   17    1    0    7    3  ...   19   92    0   
4         14   12    5    3    2    1    2    4  130   70  ...    3  127   14   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1245544   15    3    2    1    5  124  132   12    7    0  ...    0    0    0   
1245545    5    0    0    0   10   98  111   33   56    2  ...    0    0    0   
1245546   16  155   50    2    6    1    0    0   27  134  ...    0    2    0   
1245547   87   94    9    0    4   22    5   20   46   79  ...   12   10    0   
1245548    1    2    0    0    0    0    1    0    8    3  ...    0   27   76   

         121  122  123  124  125  126  127  
0          0    0    0    0    0    0    0  
1          7    6   27   14    0   10   62  
2          0    0    0    0    0    0    0  
3          0    0    0    0    5    3    1  
4         21   19    0    0    0    4    5  
...      ...  ...  ...  ...  ...  ...  ...  
1245544    0    1    0    0    0    0    0  
1245545    0    0    0    0    0    0    0  
1245546    0    0    0    0    0    0    0  
1245547    0    0    6   85   12    0    0  
1245548    0    0    9   60   12    0    7  

[1245549 rows x 128 columns]

In [ ]:
import sklearn.cluster as cluster
import seaborn as sns 

In [ ]:
import sklearn.metrics as metrics
for i in range(2,10):
    labels=cluster.KMeans(n_clusters=i,init="k-means++",random_state=200).fit(data).labels_
    print ("Silhouette score for k(clusters) = "+str(i)+" is " +str(metrics.silhouette_score(data,labels,metric="euclidean",sample_size=1000,random_state=200)))

Silhouette score for k(clusters) = 2 is 0.08018372040913249
Silhouette score for k(clusters) = 3 is 0.05403178478288946
Silhouette score for k(clusters) = 4 is 0.0480109250696534
Silhouette score for k(clusters) = 5 is 0.04750151903093386
Silhouette score for k(clusters) = 6 is 0.049444080857012726
Silhouette score for k(clusters) = 7 is 0.04802630948612109
Silhouette score for k(clusters) = 8 is 0.047470520938984594
Silhouette score for k(clusters) = 9 is 0.0467073446488975


In [ ]:
kmeans = KMeans(n_clusters=6)
kmeans.fit(data)

KMeans(n_clusters=6)

In [ ]:
import pickle

In [ ]:
filename = 'Kmeans_helmet_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,150)
    print(path)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    #hist= np.histogram(a,bins=[0,1,2,3,4,5,6,7,8])
    hist= np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'/content/drive/MyDrive/Cyclist/final_helmet1.csv', mode='a',header=False,index=False)

/content/drive/MyDrive/Cyclist/with_helmet/3888.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6589.jpg
/content/drive/MyDrive/Cyclist/with_helmet/1212.jpg
/content/drive/MyDrive/Cyclist/with_helmet/4398.jpg
/content/drive/MyDrive/Cyclist/with_helmet/3846.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6069.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6718.jpg
/content/drive/MyDrive/Cyclist/with_helmet/3451.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6824.jpg
/content/drive/MyDrive/Cyclist/with_helmet/46.jpg
/content/drive/MyDrive/Cyclist/with_helmet/2758.jpg
/content/drive/MyDrive/Cyclist/with_helmet/5192.jpg
/content/drive/MyDrive/Cyclist/with_helmet/3836.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6981.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6871.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6986.jpg
/content/drive/MyDrive/Cyclist/with_helmet/6931.jpg
/content/drive/MyDrive/Cyclist/with_helmet/503.jpg
/content/drive/MyDrive/Cyclist/with_helmet/1886.jpg
/content/drive/

In [ ]:
i=1
data=[]
#k=0

for filename in os.listdir(folder2):
    #path
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(150,150)
    print(path)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    #hist= np.histogram(a,bins=[0,1,2,3,4,5,6,7,8])
    hist= np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'/content/drive/MyDrive/Cyclist/final_nohelmet1.csv', mode='a',header=False,index=False)

/content/drive/MyDrive/Cyclist/without_helmet/1826.jpg
/content/drive/MyDrive/Cyclist/without_helmet/4764.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1933.jpg
/content/drive/MyDrive/Cyclist/without_helmet/4525.jpg
/content/drive/MyDrive/Cyclist/without_helmet/3729.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1521.jpg
/content/drive/MyDrive/Cyclist/without_helmet/4199.jpg
/content/drive/MyDrive/Cyclist/without_helmet/4185.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1507.jpg
/content/drive/MyDrive/Cyclist/without_helmet/5464.jpg
/content/drive/MyDrive/Cyclist/without_helmet/4385.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1763.jpg
/content/drive/MyDrive/Cyclist/without_helmet/5193.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1277.jpg
/content/drive/MyDrive/Cyclist/without_helmet/2144.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1628.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1537.jpg
/content/drive/MyDrive/Cyclist/without_helmet/1306.jpg
/content/d

In [ ]:
dat1= pd.read_csv(r'/content/drive/MyDrive/Cyclist/final_helmet1.csv',header=None)
print(dat1)

       0   1   2   3   4   5  6
0     31  42  66  45  64  42  0
1     38  51  68  33  18  47  0
2     16  15  26  45  41  30  0
3     19  24  30  47  16  25  0
4     11  10  12  31  11  13  0
...   ..  ..  ..  ..  ..  .. ..
5447  27  26  34  32  24  23  0
5448  22  17  31  58  27  39  0
5449  31  20  63  59  46  63  0
5450  29  36  49  48  57  40  0
5451  16  15  16  39  21  15  0

[5452 rows x 7 columns]


In [ ]:
dat2= pd.read_csv(r'/content/drive/MyDrive/Cyclist/final_nohelmet1.csv',header=None)
print(dat2)

       0   1   2   3   4   5  6
0     30  27  30  42  25  25  1
1     23  38  43  31  25  41  1
2     28  25  43  24  48  22  1
3     35  35  55  35  37  40  1
4     41  47  46  36  29  37  1
...   ..  ..  ..  ..  ..  .. ..
3287  54  47  47  30  20  44  1
3288  30  25  31  22  12  24  1
3289  22  19  41  12  14  34  1
3290  28  42  36  41  16  38  1
3291  44  61  61  27  47  50  1

[3292 rows x 7 columns]


In [ ]:
A=dat1.append(dat2)
csv_data=A.to_csv(r'/content/drive/MyDrive/Cyclist/classifier1.csv', mode='a',header=False,index=False)

In [ ]:
A


0   1   2   3   4   5  6
0     31  42  66  45  64  42  0
1     38  51  68  33  18  47  0
2     16  15  26  45  41  30  0
3     19  24  30  47  16  25  0
4     11  10  12  31  11  13  0
...   ..  ..  ..  ..  ..  .. ..
3287  54  47  47  30  20  44  1
3288  30  25  31  22  12  24  1
3289  22  19  41  12  14  34  1
3290  28  42  36  41  16  38  1
3291  44  61  61  27  47  50  1

[8744 rows x 7 columns]

In [ ]:
x = A.iloc[:,0:6].values
x

array([[31, 42, 66, 45, 64, 42],
       [38, 51, 68, 33, 18, 47],
       [16, 15, 26, 45, 41, 30],
       ...,
       [22, 19, 41, 12, 14, 34],
       [28, 42, 36, 41, 16, 38],
       [44, 61, 61, 27, 47, 50]])

In [ ]:
y = A.iloc[:,6].values
y

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
from sklearn.preprocessing import StandardScaler
xs = StandardScaler()
x_pca = xs.fit_transform(x)
x_pca

array([[ 0.13147986,  0.97640757,  1.03471199,  0.77378593,  1.53894815,
         0.4718953 ],
       [ 0.68351851,  1.67763108,  1.12860539, -0.21808782, -0.58386562,
         0.80065941],
       [-1.05146009, -1.12726294, -0.84315612,  0.77378593,  0.47754127,
        -0.31713855],
       ...,
       [-0.57828411, -0.81560805, -0.13895558, -1.95386689, -0.76845812,
        -0.05412726],
       [-0.10510813,  0.97640757, -0.3736891 ,  0.44316134, -0.67616187,
         0.20888402],
       [ 1.15669449,  2.45676831,  0.79997847, -0.7140247 ,  0.75443002,
         0.99791787]])

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=None)
pca.fit(x_pca)

PCA()

In [ ]:
cycle_pca = pca.transform(x_pca)
cycle_pca

array([[ 1.86208452,  1.12453446,  0.04643741,  0.3591365 , -0.60625568,
        -0.02146907],
       [ 1.75176243, -1.17751419,  0.07357538, -0.14623981, -0.55537982,
         0.89132099],
       [-1.23849571,  1.25837142, -0.57854288, -0.19896513, -0.07694584,
        -0.71901291],
       ...,
       [-1.34828751, -0.78218376,  1.49399642, -0.81506092,  0.19317131,
         0.25813898],
       [ 0.18253119, -0.74900312, -0.785941  ,  0.0945483 , -0.75897512,
         0.06536975],
       [ 2.60539853, -1.09703189,  0.89873027,  0.64362818, -0.93514521,
        -0.02009533]])

In [ ]:
cycle_pca = pd.DataFrame(cycle_pca)
cycle_pca

0         1         2         3         4         5
0     1.862085  1.124534  0.046437  0.359136 -0.606256 -0.021469
1     1.751762 -1.177514  0.073575 -0.146240 -0.555380  0.891321
2    -1.238496  1.258371 -0.578543 -0.198965 -0.076946 -0.719013
3    -1.220959  0.316474 -1.166419  0.019660 -0.243835  0.141610
4    -3.099280  0.183753 -0.144185 -0.004365  0.037005 -0.096422
...        ...       ...       ...       ...       ...       ...
8739  1.614860 -1.832856  0.093858  0.582846  0.421048 -0.023310
8740 -1.247744 -0.958652  0.587376  0.222267  0.324725  0.191233
8741 -1.348288 -0.782184  1.493996 -0.815061  0.193171  0.258139
8742  0.182531 -0.749003 -0.785941  0.094548 -0.758975  0.065370
8743  2.605399 -1.097032  0.898730  0.643628 -0.935145 -0.020095

[8744 rows x 6 columns]

In [ ]:
cycle_pca.shape

(8744, 6)

In [ ]:
print(pca.explained_variance_ratio_) 

[0.58693567 0.16572703 0.14870871 0.0521952  0.02423015 0.02220325]


In [ ]:
pca = PCA(n_components=6)
pca.fit(x_pca)

PCA(n_components=6)

In [ ]:
# save the model to disk
filename = 'PCA_helmet_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
cycle_pca = pca.transform(x_pca)
cycle_pca

array([[ 1.86208452,  1.12453446,  0.04643741,  0.3591365 , -0.60625568,
        -0.02146907],
       [ 1.75176243, -1.17751419,  0.07357538, -0.14623981, -0.55537982,
         0.89132099],
       [-1.23849571,  1.25837142, -0.57854288, -0.19896513, -0.07694584,
        -0.71901291],
       ...,
       [-1.34828751, -0.78218376,  1.49399642, -0.81506092,  0.19317131,
         0.25813898],
       [ 0.18253119, -0.74900312, -0.785941  ,  0.0945483 , -0.75897512,
         0.06536975],
       [ 2.60539853, -1.09703189,  0.89873027,  0.64362818, -0.93514521,
        -0.02009533]])

In [ ]:
cycle_pca.shape

(8744, 6)

In [ ]:
print(pca.explained_variance_ratio_) 

[0.58693567 0.16572703 0.14870871 0.0521952  0.02423015 0.02220325]


In [ ]:
cycle_pca = pd.DataFrame(cycle_pca)
cycle_pca

0         1         2         3         4         5
0     1.862085  1.124534  0.046437  0.359136 -0.606256 -0.021469
1     1.751762 -1.177514  0.073575 -0.146240 -0.555380  0.891321
2    -1.238496  1.258371 -0.578543 -0.198965 -0.076946 -0.719013
3    -1.220959  0.316474 -1.166419  0.019660 -0.243835  0.141610
4    -3.099280  0.183753 -0.144185 -0.004365  0.037005 -0.096422
...        ...       ...       ...       ...       ...       ...
8739  1.614860 -1.832856  0.093858  0.582846  0.421048 -0.023310
8740 -1.247744 -0.958652  0.587376  0.222267  0.324725  0.191233
8741 -1.348288 -0.782184  1.493996 -0.815061  0.193171  0.258139
8742  0.182531 -0.749003 -0.785941  0.094548 -0.758975  0.065370
8743  2.605399 -1.097032  0.898730  0.643628 -0.935145 -0.020095

[8744 rows x 6 columns]

In [ ]:
B=pd.concat([cycle_pca, pd.DataFrame(y)],axis=1)
B

0         1         2         3         4         5  0
0     1.862085  1.124534  0.046437  0.359136 -0.606256 -0.021469  0
1     1.751762 -1.177514  0.073575 -0.146240 -0.555380  0.891321  0
2    -1.238496  1.258371 -0.578543 -0.198965 -0.076946 -0.719013  0
3    -1.220959  0.316474 -1.166419  0.019660 -0.243835  0.141610  0
4    -3.099280  0.183753 -0.144185 -0.004365  0.037005 -0.096422  0
...        ...       ...       ...       ...       ...       ... ..
8739  1.614860 -1.832856  0.093858  0.582846  0.421048 -0.023310  1
8740 -1.247744 -0.958652  0.587376  0.222267  0.324725  0.191233  1
8741 -1.348288 -0.782184  1.493996 -0.815061  0.193171  0.258139  1
8742  0.182531 -0.749003 -0.785941  0.094548 -0.758975  0.065370  1
8743  2.605399 -1.097032  0.898730  0.643628 -0.935145 -0.020095  1

[8744 rows x 7 columns]

In [ ]:
csv_data=B.to_csv(r'/content/drive/MyDrive/Cyclist/FinalPCAClassifier1.csv', mode='a',header=False,index=False)

In [ ]:
data= pd.read_csv(r'/content/drive/MyDrive/Cyclist/FinalPCAClassifier1.csv',header=None)
data

0         1         2         3         4         5  6
0     1.862085  1.124534  0.046437  0.359136 -0.606256 -0.021469  0
1     1.751762 -1.177514  0.073575 -0.146240 -0.555380  0.891321  0
2    -1.238496  1.258371 -0.578543 -0.198965 -0.076946 -0.719013  0
3    -1.220959  0.316474 -1.166419  0.019660 -0.243835  0.141610  0
4    -3.099280  0.183753 -0.144185 -0.004365  0.037005 -0.096422  0
...        ...       ...       ...       ...       ...       ... ..
8739  1.614860 -1.832856  0.093858  0.582846  0.421048 -0.023310  1
8740 -1.247744 -0.958652  0.587376  0.222267  0.324725  0.191233  1
8741 -1.348288 -0.782184  1.493996 -0.815061  0.193171  0.258139  1
8742  0.182531 -0.749003 -0.785941  0.094548 -0.758975  0.065370  1
8743  2.605399 -1.097032  0.898730  0.643628 -0.935145 -0.020095  1

[8744 rows x 7 columns]

In [ ]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:6].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,6]
print("Y values")
print(y)

X values
[[ 1.86208452  1.12453446  0.04643741  0.3591365  -0.60625568 -0.02146907]
 [ 1.75176243 -1.17751419  0.07357538 -0.14623981 -0.55537982  0.89132099]
 [-1.23849571  1.25837142 -0.57854288 -0.19896513 -0.07694584 -0.71901291]
 ...
 [-1.34828751 -0.78218376  1.49399642 -0.81506092  0.19317131  0.25813898]
 [ 0.18253119 -0.74900312 -0.785941    0.0945483  -0.75897512  0.06536975]
 [ 2.60539853 -1.09703189  0.89873027  0.64362818 -0.93514521 -0.02009533]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
8739    1
8740    1
8741    1
8742    1
8743    1
Name: 6, Length: 8744, dtype: int64


In [ ]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
para = [] # list to save all parameter values to plot
acc = [] # list to save all accuracy values to plot
for i in range(10,500,10):
  rfc = RandomForestClassifier(n_estimators=i)
  rfc = rfc.fit(x_train,y_train)
  y_pred1 = rfc.predict(x_test)
  para.append(i)
  acc.append(accuracy_score(y_test, y_pred1)*100)

In [ ]:
para[acc.index(max(acc))], max(acc)

(230, 88.22184105202973)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
rfc = RandomForestClassifier(n_estimators=350)
rfc = rfc.fit(x_train,y_train)
y_pred1 = rfc.predict(x_test)
#Results
print("RandomForestClassifier Results")
print("RandomForestClassifier Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("CM = \n",confusion_matrix(y_test, y_pred1))

RandomForestClassifier Results
RandomForestClassifier Accuracy:  87.59291023441966 %
CM = 
 [[1054   44]
 [ 173  478]]


In [ ]:
# save the model to disk
filename = 'RF_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))